# Generated by Django 5.1.15 on 2026-03-11 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_follow'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='account_type',
            field=models.CharField(choices=[('guide', 'Guide'), ('traveller', 'Traveller'), ('service', 'Service Provider')], default='traveller', max_length=10),
        ),
    ]
