# Generated by Django 5.1.15 on 2026-03-11 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_experience'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='account_type',
            field=models.CharField(choices=[('traveller', 'Travellers'), ('guide', 'Guides'), ('service', 'Services')], default='traveller', max_length=10),
        ),
    ]
