# Generated by Django 5.1.15 on 2026-04-19 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_providerreview'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='opt_out_discovery',
            field=models.BooleanField(default=False, help_text='If true, the user will not appear in search or discovery algorithms.'),
        ),
    ]
