# Generated by Django 5.1.15 on 2026-04-19 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_customuser_opt_out_discovery'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='show_followers_list',
            field=models.BooleanField(default=True, help_text="Whether other users can see this user's followers/following lists."),
        ),
    ]
