# Generated by Django 5.1.15 on 2026-04-20 02:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='onboarding_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='verification_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='pending', max_length=10),
        ),
        migrations.CreateModel(
            name='TravelerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interests', models.JSONField(default=list, help_text="e.g. ['adventure', 'culture', 'food']")),
                ('past_history', models.TextField(blank=True, help_text='Countries/cities visited, frequency')),
                ('future_intentions', models.TextField(blank=True, help_text='Destinations, timelines, preferences')),
                ('job_industry', models.CharField(blank=True, max_length=100)),
                ('travel_flexibility', models.CharField(blank=True, help_text='Flexibility for travel', max_length=50)),
                ('budget_range', models.CharField(blank=True, help_text='e.g. Luxury, Mid-range, Budget', max_length=50)),
                ('travel_style', models.CharField(blank=True, help_text='e.g. Backpacker, Organized', max_length=50)),
                ('group_preference', models.CharField(blank=True, help_text='Group vs solo travel preferences', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='traveler_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='VerificationDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('id', 'Government Issued ID'), ('visa', 'Residency/Visa Documentation (UAE)'), ('license', 'Professional Guide License'), ('other', 'Other')], max_length=20)),
                ('file', models.FileField(upload_to='verification_docs/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verification_documents', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
