# Generated by Django 5.1.15 on 2026-04-21 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_alter_booking_unique_together_booking_source_post_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='experienceimage',
            options={'ordering': ['order', 'created_at']},
        ),
        migrations.AddField(
            model_name='experienceimage',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
