# Generated by Django 5.1.15 on 2026-04-22 01:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_alter_experienceimage_options_experienceimage_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuideAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('is_available', models.BooleanField(default=False, help_text='False means blackout date')),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availability', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Guide Availabilities',
                'unique_together': {('user', 'date')},
            },
        ),
    ]
