# Generated by Django 5.1.15 on 2026-04-22 02:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_guideavailability'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='listing_type',
            field=models.CharField(choices=[('experience', 'Experience (Fun)'), ('service', 'Service (Essentials)')], default='experience', max_length=20),
        ),
        migrations.AlterField(
            model_name='booking',
            name='provider',
            field=models.ForeignKey(limit_choices_to={'account_type': 'guide'}, on_delete=django.db.models.deletion.CASCADE, related_name='provider_bookings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='account_type',
            field=models.CharField(choices=[('traveller', 'Travellers'), ('guide', 'Guides')], default='traveller', max_length=10),
        ),
        migrations.AlterField(
            model_name='experience',
            name='category',
            field=models.CharField(choices=[('Adventure', 'Adventure'), ('Culture', 'Culture'), ('Nightlife', 'Nightlife'), ('History', 'History'), ('Nature', 'Nature'), ('Gastronomy', 'Gastronomy'), ('Transportation', 'Transportation'), ('Housing', 'Housing'), ('Documentation', 'Documentation'), ('Connectivity', 'Connectivity'), ('Local Support', 'Local Support'), ('Other', 'Other')], default='Cultural', max_length=100),
        ),
        migrations.AlterField(
            model_name='experience',
            name='user',
            field=models.ForeignKey(limit_choices_to={'account_type': 'guide'}, on_delete=django.db.models.deletion.CASCADE, related_name='experiences', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='providerreview',
            name='provider',
            field=models.ForeignKey(limit_choices_to={'account_type': 'guide'}, on_delete=django.db.models.deletion.CASCADE, related_name='provider_reviews', to=settings.AUTH_USER_MODEL),
        ),
    ]
