# Generated by Django 5.1.15 on 2026-07-31 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_alter_customuser_phone_no_alter_customuser_whatsapp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_picture',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to='profile_pics/'),
        ),
    ]
