# Generated by Django 5.1.15 on 2026-02-10 08:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video')], help_text='Type of media (image or video) in the post.', max_length=10)),
                ('media_url', models.URLField(help_text='URL of the media content (image or video).', max_length=2000)),
                ('aspect_ratio', models.CharField(blank=True, help_text="Aspect ratio of the media (e.g., '1:1', '4:5').", max_length=10, null=True)),
                ('caption', models.TextField(blank=True, help_text='The text caption accompanying the post.')),
                ('likes_count', models.PositiveIntegerField(default=0, help_text='Number of likes the post has received.')),
                ('comments_count', models.PositiveIntegerField(default=0, help_text='Number of comments on the post. (Note: Actual comments would be a separate model).')),
                ('saves_count', models.PositiveIntegerField(default=0, help_text='Number of times the post has been saved by users.')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='The date and time when the post was created.')),
                ('user', models.ForeignKey(help_text='The user who created this post.', on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Post',
                'verbose_name_plural': 'Posts',
                'ordering': ['-created_at'],
            },
        ),
    ]
