# Generated by Django 5.1.15 on 2026-03-08 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_trip'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='text_alignment',
            field=models.CharField(choices=[('left', 'Left'), ('center', 'Center'), ('right', 'Right')], default='center', help_text='Alignment of the text in text-only posts.', max_length=10),
        ),
    ]
