# Generated by Django 5.1.15 on 2026-04-12 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_comment_like_save'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='category',
            field=models.CharField(choices=[('Adventure', 'Adventure'), ('Relaxing', 'Relaxing'), ('Cultural', 'Cultural'), ('Food', 'Food'), ('Nature', 'Nature'), ('Business', 'Business'), ('Other', 'Other')], default='Adventure', max_length=50),
        ),
    ]
