# Generated by Django 5.1.15 on 2026-04-19 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_trip_destination_country_trip_region'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='audience',
            field=models.CharField(choices=[('public', 'Public'), ('followers', 'Followers'), ('friends', 'Friends'), ('private', 'Private')], default='public', help_text='The audience for this post.', max_length=10),
        ),
    ]
