# Generated by Django 5.1.15 on 2026-04-21 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_postimage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='postimage',
            options={'ordering': ['order', 'created_at']},
        ),
        migrations.AddField(
            model_name='postimage',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
