# Generated by Django 5.1.15 on 2026-04-23 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0010_alter_postimage_options_postimage_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='category',
            field=models.CharField(choices=[('Adventure', 'Adventure'), ('Relaxing', 'Relaxing'), ('Cultural', 'Cultural'), ('Food', 'Food'), ('Nature', 'Nature'), ('Business', 'Business'), ('Shopping', 'Shopping'), ('Religious', 'Religious'), ('Safari', 'Safari'), ('Coastal', 'Coastal'), ('Luxury', 'Luxury'), ('Wellness', 'Wellness'), ('Sports', 'Sports'), ('Other', 'Other')], default='Adventure', max_length=50),
        ),
    ]
