# Generated by Django 5.1.15 on 2026-04-27 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0011_alter_trip_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='current_travelers',
            field=models.PositiveIntegerField(default=1, help_text='Current number of people joined'),
        ),
        migrations.AddField(
            model_name='trip',
            name='max_travelers',
            field=models.PositiveIntegerField(default=4, help_text='Maximum number of people for this trip'),
        ),
    ]
