# Generated by Django 5.1.15 on 2026-02-05 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guide_registration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='guideinterest',
            name='nationality',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
