# Generated by Django 5.1.15 on 2026-04-12 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_passwordresettoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='category',
            field=models.CharField(choices=[('Cultural', 'Cultural'), ('Adventure', 'Adventure'), ('Food', 'Food'), ('Nature', 'Nature'), ('Other', 'Other')], default='Cultural', max_length=100),
        ),
    ]
