# Generated by Django 5.1.15 on 2026-04-20 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_customuser_onboarding_completed_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='travelerprofile',
            name='past_history',
        ),
        migrations.AddField(
            model_name='travelerprofile',
            name='past_adventures',
            field=models.JSONField(default=list, help_text='List of objects: {country, purpose, duration, motivation}'),
        ),
        migrations.AlterField(
            model_name='travelerprofile',
            name='future_intentions',
            field=models.JSONField(default=list, help_text='List of objects: {destination, timeline, purpose, motivation}'),
        ),
    ]
