# Generated by Django 5.1.15 on 2026-04-23 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_experience_listing_type_alter_booking_provider_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='category',
            field=models.CharField(choices=[('Adventure', 'Adventure'), ('Culture', 'Culture'), ('Nightlife', 'Nightlife'), ('History', 'History'), ('Nature', 'Nature'), ('Gastronomy', 'Gastronomy'), ('Shopping & Souks', 'Shopping & Souks'), ('Religious & Heritage', 'Religious & Heritage'), ('Desert & Safari', 'Desert & Safari'), ('Coastal & Marine', 'Coastal & Marine'), ('Luxury & VIP', 'Luxury & VIP'), ('Wellness & Spa', 'Wellness & Spa'), ('Sports & Events', 'Sports & Events'), ('Transportation', 'Transportation'), ('Housing', 'Housing'), ('Documentation', 'Documentation'), ('Connectivity', 'Connectivity'), ('Local Support', 'Local Support'), ('Other', 'Other')], default='Cultural', max_length=100),
        ),
    ]
