FROM postgres:17-alpine
# Set default environment variables
ENV POSTGRES_DB=linklerdb \
    POSTGRES_USER=tsegazeab \
    POSTGRES_PASSWORD=Abebebesobela424*

# Copy custom initialization SQL scripts if any
# COPY ./init.sql /docker-entrypoint-initdb.d/

EXPOSE 5432
