# Generated by Django 5.1.15 on 2026-02-10 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='media_url',
        ),
        migrations.AddField(
            model_name='post',
            name='allow_comments',
            field=models.BooleanField(default=True, help_text='Whether users can comment on this post.'),
        ),
        migrations.AddField(
            model_name='post',
            name='audience',
            field=models.CharField(choices=[('public', 'Public'), ('followers', 'Followers'), ('private', 'Private')], default='public', help_text='The audience for this post.', max_length=10),
        ),
        migrations.AddField(
            model_name='post',
            name='media_file',
            field=models.FileField(blank=True, help_text='The actual media file, uploaded by the user.', null=True, upload_to='post_media/'),
        ),
        migrations.AddField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='published', help_text='The status of the post (e.g., draft, published).', max_length=10),
        ),
        migrations.AlterField(
            model_name='post',
            name='comments_count',
            field=models.PositiveIntegerField(default=0, help_text='Number of comments on the post.'),
        ),
        migrations.AlterField(
            model_name='post',
            name='media_type',
            field=models.CharField(blank=True, choices=[('image', 'Image'), ('video', 'Video')], help_text='Type of media (image or video) in the post.', max_length=10, null=True),
        ),
    ]
