# Generated by Django 5.1.15 on 2026-04-19 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_alter_post_audience'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='country',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='post',
            name='region',
            field=models.CharField(blank=True, choices=[('Africa', 'Africa'), ('Asia', 'Asia'), ('Europe', 'Europe'), ('North America', 'North America'), ('South America', 'South America'), ('Oceania', 'Oceania'), ('Middle East', 'Middle East')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='trip_images/'),
        ),
    ]
