# Generated by Django 5.1.15 on 2026-07-31 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0010_alter_postimage_options_postimage_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='media_file',
            field=models.FileField(blank=True, help_text='The actual media file, uploaded by the user.', max_length=500, null=True, upload_to='post_media/'),
        ),
    ]
