# Generated by Django 5.1.15 on 2026-07-31 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0011_alter_post_media_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postimage',
            name='image',
            field=models.ImageField(max_length=500, upload_to='post_images/'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='image',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to='trip_images/'),
        ),
    ]
