# Generated by Django 5.1.15 on 2026-08-04 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0013_alter_post_media_file_alter_postimage_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='media_file',
            field=models.FileField(blank=True, help_text='The actual media file, uploaded by the user.', max_length=500, null=True, upload_to='post_media/'),
        ),
        migrations.AlterField(
            model_name='postimage',
            name='image',
            field=models.ImageField(max_length=500, upload_to='post_images/'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='image',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to='trip_images/'),
        ),
    ]
