# Generated by Django 5.1.15 on 2026-04-06 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discovery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotion',
            name='category',
            field=models.CharField(choices=[('Hotels', 'Hotels'), ('Restaurants', 'Restaurants'), ('Bars', 'Bars'), ('Travel', 'Travel'), ('Activities', 'Activities')], default='Travel', max_length=50),
        ),
    ]
