# Generated by Django 5.1.15 on 2026-04-12 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discovery', '0003_promotion_currency_promotion_original_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotion',
            name='country',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='promotion',
            name='region',
            field=models.CharField(choices=[('Africa', 'Africa'), ('Asia', 'Asia'), ('Europe', 'Europe'), ('North America', 'North America'), ('South America', 'South America'), ('Oceania', 'Oceania'), ('Middle East', 'Middle East')], default='Europe', max_length=50),
        ),
    ]
