# Generated by Django 5.1.15 on 2026-04-23 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discovery', '0005_promotionimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promotion',
            name='category',
            field=models.CharField(choices=[('Hotels', 'Hotels'), ('Restaurants', 'Restaurants'), ('Bars', 'Bars'), ('Travel', 'Travel'), ('Activities', 'Activities'), ('Shopping', 'Shopping'), ('Religious', 'Religious'), ('Safari', 'Safari'), ('Coastal', 'Coastal'), ('Luxury', 'Luxury'), ('Wellness', 'Wellness'), ('Sports', 'Sports'), ('Other', 'Other')], default='Travel', max_length=50),
        ),
    ]
